# PowerShell equivalent of scripts/bench.sh.
#
# scripts/bench.sh is bash-only and calls `/proc/self/status` (VmHWM) for
# peak RSS, which doesn't exist on Windows -- examples/bench.rs already
# handles that itself (see its `peak RSS unavailable on this platform`
# fallback), so this script doesn't need to special-case it either.
#
# Usage:
#   powershell -File scripts/bench.ps1
#
# Writes bench/results.md, same format as the bash version.

$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent $PSScriptRoot
Set-Location $Root
New-Item -ItemType Directory -Force -Path "bench" | Out-Null

Write-Host "==> Building release binary"
cargo build --release --example bench
if ($LASTEXITCODE -ne 0) { throw "cargo build failed" }

Write-Host "==> Running Rust benchmarks"
$RustOut = (cargo run --release --example bench) -join "`n"
if ($LASTEXITCODE -ne 0) { throw "cargo run failed" }
Write-Host $RustOut

$NodePerSec = "unavailable"
$HaveNode = Get-Command node -ErrorAction SilentlyContinue
if ((Test-Path "vendor\node-semver") -and $HaveNode) {
    Write-Host ""
    Write-Host "==> Running the original for comparison"
    $NodeJson = node bench/compare.js
    $NodePerSec = ($NodeJson | ConvertFrom-Json).perSec
    Write-Host "    original: $NodePerSec versions/sec"
}

$SustainedLine = ($RustOut -split "`n") | Where-Object { $_ -match "sustained parse" } | Select-Object -Last 1
$RustPerSec = [regex]::Match($SustainedLine, '(\d+)\s+versions/sec').Groups[1].Value

$Lines = @()
$Lines += "# Benchmark results"
$Lines += ""
$Lines += "Generated by ``scripts/bench.ps1`` on $((Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ'))."
$Lines += ""
$Lines += '```'
$Lines += $RustOut
$Lines += '```'
$Lines += ""

if ($NodePerSec -ne "unavailable") {
    $Ratio = "{0:N1}" -f ([double]$RustPerSec / [double]$NodePerSec)
    $Lines += "## Against the original"
    $Lines += ""
    $Lines += "Same corpus, same 500ms budget, both warmed up first."
    $Lines += ""
    $Lines += "| | versions/sec |"
    $Lines += "|---|---|"
    $Lines += "| semver-rs | $RustPerSec |"
    $Lines += "| node-semver | $NodePerSec |"
    $Lines += "| ratio | ${Ratio}x |"
    $Lines += ""
    $Lines += "Only throughput is compared. A single-shot latency number for a"
    $Lines += "Node script is dominated by process startup and would say nothing"
    $Lines += "about the library itself."
}

$Lines += ""
$Lines += "## Method"
$Lines += ""
$Lines += "Percentiles rather than a mean: parse latency is right-skewed, and"
$Lines += "a mean hides the tail. Each measurement warms up for a tenth of its"
$Lines += "iteration count before sampling. Peak RSS is read from"
$Lines += "``/proc/self/status`` (``VmHWM``) on Linux; unavailable on Windows,"
$Lines += "where examples/bench.rs reports so explicitly instead of a fake 0."

$Lines -join "`n" | Set-Content -Path "bench\results.md" -NoNewline

Write-Host ""
Write-Host "Written to bench\results.md"
