#!/usr/bin/env bash
# Benchmarks for semver-rs, plus a throughput comparison against the
# original running under Node.
#
#   bash scripts/bench.sh
#
# Writes bench/results.md.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
mkdir -p bench

echo "==> Building release binary"
cargo build --release --example bench 2>&1 | tail -1

echo "==> Running Rust benchmarks"
RUST_OUT=$(cargo run --release --example bench 2>/dev/null)
echo "$RUST_OUT"

NODE_PER_SEC="unavailable"
if [ -d vendor/node-semver ] && command -v node >/dev/null 2>&1; then
  echo
  echo "==> Running the original for comparison"
  NODE_JSON=$(node bench/compare.js)
  NODE_PER_SEC=$(echo "$NODE_JSON" | sed 's/.*"perSec":\([0-9]*\).*/\1/')
  echo "    original: $NODE_PER_SEC versions/sec"
fi

RUST_PER_SEC=$(echo "$RUST_OUT" | grep "sustained parse" | tail -1 | grep -oE '[0-9]+' | tail -1)

{
  echo "# Benchmark results"
  echo
  echo "Generated by \`scripts/bench.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo
  echo '```'
  echo "$RUST_OUT"
  echo '```'
  echo
  if [ "$NODE_PER_SEC" != "unavailable" ]; then
    RATIO=$(awk -v r="$RUST_PER_SEC" -v n="$NODE_PER_SEC" 'BEGIN { printf "%.1f", r/n }')
    echo "## Against the original"
    echo
    echo "Same corpus, same 500ms budget, both warmed up first."
    echo
    echo "| | versions/sec |"
    echo "|---|---|"
    echo "| semver-rs | $RUST_PER_SEC |"
    echo "| node-semver | $NODE_PER_SEC |"
    echo "| ratio | ${RATIO}x |"
    echo
    echo "Only throughput is compared. A single-shot latency number for a"
    echo "Node script is dominated by process startup and would say nothing"
    echo "about the library itself."
  fi
  echo
  echo "## Method"
  echo
  echo "Percentiles rather than a mean: parse latency is right-skewed, and"
  echo "a mean hides the tail. Each measurement warms up for a tenth of its"
  echo "iteration count before sampling. Peak RSS is read from"
  echo "\`/proc/self/status\` (\`VmHWM\`)."
} > bench/results.md

echo
echo "Written to bench/results.md"
